### ISSUE TITLE
Provide a way to pull in the schema from platform.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/web-extension-manifest-schema#14]
We have the schema here platform has one being built out in mozilla-central. When everything's in less of a state of flux we should consolidate. For example we'll probably be looking to do an import of the mozilla-central schema as opposed to manually keeping them up to date.

**Comment by andymckay** [comment]
Probably moving mozilla-central to v4 is probably the first step https://bugzilla.mozilla.org/show_bug.cgi?id=1243516

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-linter/issues/765
