### ISSUE TITLE
Beta string versions should be allowed

### ISSUE THREAD

**Issue by raphaelfaria** [mozilla/web-extension-manifest-schema#144]
The schema currently supports only integer numbers on version parts and prevents the signing of beta versions of web extensions.
It should allow this match `(a|alpha|b|beta|pre|rc)\d*$` at the last version part as described in: https://developer.mozilla.org/en-US/docs/Toolkit_version_format and https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance

**Comment by muffinresearch** [comment]
This issue has been moved here [1]  as the schema is now part of addons-linter. 

[1] https://github.com/mozilla/addons-linter/issues/764
