### ISSUE TITLE
Provide encapsulated validator

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-extension-manifest-schema#29]
If I'm reading the addons-linter code correctly, there is no way to get an encapsulated instance of a validated manifest. You instead do it as a singleton, like:
````
import validate from 'mozilla-web-extension-manifest-schema';

validate(someManifestJson);
console.log(validate.errors);
````
This isn't very nice for unit testing because you could have leakage from a previous validation. What I'd like is something more similar to:
````
import validate from 'mozilla-web-extension-manifest-schema';

let result = validate(someManifestJson);
console.log(result.errors);

let otherResult = validate(otherManifestJson);
console.log(otherResult.errors);
````

**Comment by muffinresearch** [comment]
It will work like your second examples, every call to validate overrides the previous errors. 

See https://github.com/epoberezkin/ajv#getting-started

> Please note: every time validation function or ajv.validate are called errors property is overwritten. You need to copy errors array reference to another variable if you want to use it later (e.g., in the callback). See Validation errors

**Comment by kumar303** [comment]
Huh. OK. That's confusing. Well, we can close the issue then I guess.
